spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/springMicroservices
    username: root
    password: root
  application:
    name: DEPARTMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry : true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost